name: run-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.1
      - name: Run Dart tests
        run: dart pdu_test.dart

